/**
 * 垃圾分类数据集
 * 四大分类：recyclable(可回收物) / kitchen(厨余垃圾) / hazardous(有害垃圾) / other(其他垃圾)
 */

const CATEGORIES = {
  recyclable: {
    key: 'recyclable',
    name: '可回收物',
    emoji: '♻️',
    color: '#2196F3',
    bgColor: '#E3F2FD',
    borderColor: '#90CAF9',
    desc: '适宜回收和资源化利用的废弃物',
    detail: '包括废纸、废塑料、废玻璃、废金属、废织物、废电器电子产品等'
  },
  kitchen: {
    key: 'kitchen',
    name: '厨余垃圾',
    emoji: '🍂',
    color: '#4CAF50',
    bgColor: '#E8F5E9',
    borderColor: '#A5D6A7',
    desc: '易腐烂的有机生活废弃物',
    detail: '包括剩菜剩饭、瓜皮果核、花卉绿植、过期食品等'
  },
  hazardous: {
    key: 'hazardous',
    name: '有害垃圾',
    emoji: '☣️',
    color: '#F44336',
    bgColor: '#FFEBEE',
    borderColor: '#EF9A9A',
    desc: '对健康和环境有害的废弃物',
    detail: '包括废电池、废灯管、废药品、废油漆、废杀虫剂等'
  },
  other: {
    key: 'other',
    name: '其他垃圾',
    emoji: '🗑️',
    color: '#9E9E9E',
    bgColor: '#F5F5F5',
    borderColor: '#BDBDBD',
    desc: '除上述三类之外的生活废弃物',
    detail: '包括餐巾纸、卫生纸、烟蒂、陶瓷碎片、一次性餐具、尘土等'
  }
};

const garbageData = [
  // ========== 可回收物 recyclable ==========
  { name: '废纸', category: 'recyclable' },
  { name: '报纸', category: 'recyclable' },
  { name: '杂志', category: 'recyclable' },
  { name: '书本', category: 'recyclable' },
  { name: '纸箱', category: 'recyclable' },
  { name: '纸板', category: 'recyclable' },
  { name: '打印纸', category: 'recyclable' },
  { name: '信封', category: 'recyclable' },
  { name: '广告单', category: 'recyclable' },
  { name: '塑料瓶', category: 'recyclable' },
  { name: '矿泉水瓶', category: 'recyclable' },
  { name: '饮料瓶', category: 'recyclable' },
  { name: '塑料桶', category: 'recyclable' },
  { name: '塑料盆', category: 'recyclable' },
  { name: '塑料玩具', category: 'recyclable' },
  { name: '塑料衣架', category: 'recyclable' },
  { name: '塑料袋（干净）', category: 'recyclable' },
  { name: '保鲜膜（干净）', category: 'recyclable' },
  { name: '塑料餐具（干净）', category: 'recyclable' },
  { name: '泡沫塑料', category: 'recyclable' },
  { name: '玻璃瓶', category: 'recyclable' },
  { name: '玻璃杯', category: 'recyclable' },
  { name: '玻璃窗', category: 'recyclable' },
  { name: '镜子', category: 'recyclable' },
  { name: '罐头盒', category: 'recyclable' },
  { name: '易拉罐', category: 'recyclable' },
  { name: '金属罐', category: 'recyclable' },
  { name: '铁钉', category: 'recyclable' },
  { name: '铁丝', category: 'recyclable' },
  { name: '废铁', category: 'recyclable' },
  { name: '废铜', category: 'recyclable' },
  { name: '废铝', category: 'recyclable' },
  { name: '废钢', category: 'recyclable' },
  { name: '不锈钢', category: 'recyclable' },
  { name: '旧衣服', category: 'recyclable' },
  { name: '旧鞋子', category: 'recyclable' },
  { name: '旧帽子', category: 'recyclable' },
  { name: '床单', category: 'recyclable' },
  { name: '被套', category: 'recyclable' },
  { name: '毛巾', category: 'recyclable' },
  { name: '书包', category: 'recyclable' },
  { name: '布包', category: 'recyclable' },
  { name: '手机', category: 'recyclable' },
  { name: '电脑', category: 'recyclable' },
  { name: '平板电脑', category: 'recyclable' },
  { name: '电视机', category: 'recyclable' },
  { name: '冰箱', category: 'recyclable' },
  { name: '洗衣机', category: 'recyclable' },
  { name: '空调', category: 'recyclable' },
  { name: '电风扇', category: 'recyclable' },
  { name: '微波炉', category: 'recyclable' },
  { name: '电饭煲', category: 'recyclable' },
  { name: '打印机', category: 'recyclable' },
  { name: '键盘', category: 'recyclable' },
  { name: '鼠标', category: 'recyclable' },
  { name: '充电器', category: 'recyclable' },
  { name: '数据线', category: 'recyclable' },
  { name: 'U盘', category: 'recyclable' },
  { name: '光盘', category: 'recyclable' },
  { name: '电路板', category: 'recyclable' },
  { name: '铝箔', category: 'recyclable' },
  { name: '铜线', category: 'recyclable' },

  // ========== 厨余垃圾 kitchen ==========
  { name: '剩饭', category: 'kitchen' },
  { name: '剩菜', category: 'kitchen' },
  { name: '面包', category: 'kitchen' },
  { name: '蛋糕', category: 'kitchen' },
  { name: '饼干', category: 'kitchen' },
  { name: '米饭', category: 'kitchen' },
  { name: '面条', category: 'kitchen' },
  { name: '馒头', category: 'kitchen' },
  { name: '蔬菜叶子', category: 'kitchen' },
  { name: '菜叶', category: 'kitchen' },
  { name: '菜根', category: 'kitchen' },
  { name: '烂菜叶', category: 'kitchen' },
  { name: '瓜皮', category: 'kitchen' },
  { name: '果皮', category: 'kitchen' },
  { name: '果核', category: 'kitchen' },
  { name: '苹果核', category: 'kitchen' },
  { name: '香蕉皮', category: 'kitchen' },
  { name: '橘子皮', category: 'kitchen' },
  { name: '西瓜皮', category: 'kitchen' },
  { name: '鸡蛋壳', category: 'kitchen' },
  { name: '蛋壳', category: 'kitchen' },
  { name: '骨头', category: 'kitchen' },
  { name: '鱼骨', category: 'kitchen' },
  { name: '鸡骨', category: 'kitchen' },
  { name: '猪骨', category: 'kitchen' },
  { name: '虾壳', category: 'kitchen' },
  { name: '蟹壳', category: 'kitchen' },
  { name: '贝壳', category: 'kitchen' },
  { name: '过期食品', category: 'kitchen' },
  { name: '过期零食', category: 'kitchen' },
  { name: '过期调料', category: 'kitchen' },
  { name: '茶渣', category: 'kitchen' },
  { name: '茶叶渣', category: 'kitchen' },
  { name: '咖啡渣', category: 'kitchen' },
  { name: '中药渣', category: 'kitchen' },
  { name: '花卉', category: 'kitchen' },
  { name: '绿植', category: 'kitchen' },
  { name: '盆栽', category: 'kitchen' },
  { name: '落叶', category: 'kitchen' },
  { name: '枯枝', category: 'kitchen' },
  { name: '豆腐', category: 'kitchen' },
  { name: '动物内脏', category: 'kitchen' },
  { name: '鱼鳞', category: 'kitchen' },
  { name: '过期食用油', category: 'kitchen' },
  { name: '果酱', category: 'kitchen' },
  { name: '宠物饲料', category: 'kitchen' },

  // ========== 有害垃圾 hazardous ==========
  { name: '废电池', category: 'hazardous' },
  { name: '充电电池', category: 'hazardous' },
  { name: '纽扣电池', category: 'hazardous' },
  { name: '锂电池', category: 'hazardous' },
  { name: '手机电池', category: 'hazardous' },
  { name: '蓄电池', category: 'hazardous' },
  { name: '废灯管', category: 'hazardous' },
  { name: '日光灯管', category: 'hazardous' },
  { name: '节能灯', category: 'hazardous' },
  { name: '灯泡', category: 'hazardous' },
  { name: '水银温度计', category: 'hazardous' },
  { name: '体温计', category: 'hazardous' },
  { name: '血压计', category: 'hazardous' },
  { name: '废药品', category: 'hazardous' },
  { name: '过期药品', category: 'hazardous' },
  { name: '废药片', category: 'hazardous' },
  { name: '药剂瓶', category: 'hazardous' },
  { name: '废油漆', category: 'hazardous' },
  { name: '油漆桶', category: 'hazardous' },
  { name: '废杀虫剂', category: 'hazardous' },
  { name: '杀虫剂罐', category: 'hazardous' },
  { name: '农药瓶', category: 'hazardous' },
  { name: '废相片', category: 'hazardous' },
  { name: '废底片', category: 'hazardous' },
  { name: '废胶卷', category: 'hazardous' },
  { name: '打印机墨盒', category: 'hazardous' },
  { name: '废硒鼓', category: 'hazardous' },
  { name: '废化妆品', category: 'hazardous' },
  { name: '过期化妆品', category: 'hazardous' },
  { name: '指甲油', category: 'hazardous' },
  { name: '洗甲水', category: 'hazardous' },
  { name: '废矿物油', category: 'hazardous' },
  { name: '废机油', category: 'hazardous' },
  { name: '废溶剂', category: 'hazardous' },
  { name: '废荧光剂', category: 'hazardous' },
  { name: '废消毒剂', category: 'hazardous' },

  // ========== 其他垃圾 other ==========
  { name: '餐巾纸', category: 'other' },
  { name: '卫生纸', category: 'other' },
  { name: '湿纸巾', category: 'other' },
  { name: '纸尿裤', category: 'other' },
  { name: '卫生巾', category: 'other' },
  { name: '烟蒂', category: 'other' },
  { name: '烟灰', category: 'other' },
  { name: '陶瓷碎片', category: 'other' },
  { name: '碎陶瓷', category: 'other' },
  { name: '碎碗', category: 'other' },
  { name: '瓦片', category: 'other' },
  { name: '一次性餐具', category: 'other' },
  { name: '一次性筷子', category: 'other' },
  { name: '一次性餐盒', category: 'other' },
  { name: '一次性杯子', category: 'other' },
  { name: '塑料袋（脏）', category: 'other' },
  { name: '保鲜膜（脏）', category: 'other' },
  { name: '大骨头', category: 'other' },
  { name: '硬骨头', category: 'other' },
  { name: '核桃壳', category: 'other' },
  { name: '椰子壳', category: 'other' },
  { name: '榴莲壳', category: 'other' },
  { name: '口香糖', category: 'other' },
  { name: '头发', category: 'other' },
  { name: '毛发', category: 'other' },
  { name: '指甲', category: 'other' },
  { name: '尘土', category: 'other' },
  { name: '灰土', category: 'other' },
  { name: '猫砂', category: 'other' },
  { name: '宠物粪便', category: 'other' },
  { name: '创可贴', category: 'other' },
  { name: '胶带', category: 'other' },
  { name: '胶水', category: 'other' },
  { name: '橡皮泥', category: 'other' },
  { name: '蜡笔', category: 'other' },
  { name: '铅笔屑', category: 'other' },
  { name: '粉笔', category: 'other' },
  { name: '贴纸', category: 'other' },
  { name: '口哨', category: 'other' },
  { name: '干燥剂', category: 'other' },
  { name: '海绵', category: 'other' },
  { name: '橡皮筋', category: 'other' },
  { name: '便利贴', category: 'other' },
  { name: '复写纸', category: 'other' },
  { name: '热敏纸', category: 'other' },
  { name: '照片纸', category: 'other' },
  { name: '气球', category: 'other' },
  { name: '竹签', category: 'other' },
  { name: '牙签', category: 'other' },
  { name: '棉花棒', category: 'other' }
];

// 热门/常见易混淆垃圾
const hotItems = [
  { name: '餐巾纸', category: 'other', tip: '水溶性太强，不可回收' },
  { name: '大骨头', category: 'other', tip: '质地坚硬，不易腐烂' },
  { name: '塑料瓶', category: 'recyclable', tip: '记得清洗干净再扔哦' },
  { name: '废电池', category: 'hazardous', tip: '重金属污染，需专门回收' },
  { name: '过期药品', category: 'hazardous', tip: '不可随意丢弃' },
  { name: '果皮', category: 'kitchen', tip: '易腐有机废弃物' },
  { name: '榴莲壳', category: 'other', tip: '质地太硬，属其他垃圾' },
  { name: '创可贴', category: 'other', tip: '沾染少量药物，属其他垃圾' },
  { name: '茶叶渣', category: 'kitchen', tip: '沥干水后投入厨余垃圾' },
  { name: '一次性餐具', category: 'other', tip: '被污染且不易回收' }
];
